services:
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
      - TIMER=3,4
      - ROOT_DIR=results3
      - SIZE=5
      - FORMAT=CSV
    container_name: api-service
    depends_on:
      - init

  init:
    build:
      context: .
      dockerfile: src/init/Dockerfile
    container_name: init-service
